### Add Order
POST http://localhost:5000/api/orders
Content-Type: application/json
token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWU1NzM2ZWZmYjgxZTYzOWJhMzg3YiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY3MjAwNjA1MSwiZXhwIjoxNjcyMjY1MjUxfQ.6tNfrZwwPAYNj2253kqYSYIJ-0wPnjnk8Db1dV9tV8I

{
    "userId":"639123cc9fc90f6a40ecaee5",
    "products":[
        {
            "productId":"21ewef",
            "quantity":2
        },
        {
            "productId":"21ewefasdasd",
            "quantity":1
        }
    ],
    "amount":100,
    "address":"USA"
}

### Order stats
GET http://localhost:5000/api/orders/income
Content-Type: application/json
token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzOWU1NzM2ZWZmYjgxZTYzOWJhMzg3YiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY3MjE2MjI0NSwiZXhwIjoxNjcyNDIxNDQ1fQ.llaKwpDGLlQ2cwNCCPgZ5n4YxqWEZaPB81I_Kcukz6Q

{}